spring.application.name=major-api
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:majorapi
spring.datasource.username=sa
spring.datasource.password=